### ISSUE TITLE
Placement file issue reported by JLCPB

### ISSUE THREAD

**Issue by coelholm** [zapta/simple_stepper_motor_analyzer#3]
I have ordered the PCB from JLCPCB using production files from https://github.com/zapta/simple_stepper_motor_analyzer/tree/main/kicad/JLCPCB

They found placement minor issues with FPC1 and FPC2. From pictures looks like FPC1 is flipped horizontally, but I couldn't figure out any correction of FPC2.

It was corrected by JLCPCB before production, but I would like to let you know.

**Comment by coelholm** [comment]
Original Placement:
![Original placement](https://raw.githubusercontent.com/coelholm/simple_stepper_motor_analyzer/main/www/Produce_SMT_Original.png)
&nbsp;
Adjusted Placement:
![Adjusted placement](https://raw.githubusercontent.com/coelholm/simple_stepper_motor_analyzer/main/www/Produce_SMT_Snapshot.png)

**Comment by coelholm** [comment]
I will update you once it arrive and I have chance to test it.

**Comment by zapta** [comment]
This is exactly what happened with my order but I verified their correction
and it seemed ok and when the boards worked with no problem.

I presume that they use the footprints from Easy EDA where they have
different center and orientation then the Kicad footprints I used.

**Comment by zapta** [comment]
BTW, two assembly hints:

1. I recommend this 10mm double side tape. I use it for the Pico, avoid it
touching the main PCB, and for the TFT.  Available also from Aliexpress and
other sites.

https://www.amazon.com/gp/product/B072JJD2ND

2. Check the 3D directory for the STL file of the 3D printed connector jig.
I use it to cut the stepper connectors pins to the right side, keeping the
TFT side of the PCB flat.

3. I recently added a 3D model for an enclosure that doesn't need heat set
threaded inserts. Easier to build and good enough.

4. For firmware binary I recommend using the one from the latest firmware
release. (unless you want to modify and compile yourself).

Please let me know if you encounter any issues.

**Comment by coelholm** [comment]
Thank you for those hints. I've order that tape and for sure that guide will help to cut connector.

**Comment by zapta** [comment]
Please see if you can get from JLCPCB the corrected placement file and then
send me a pull request so others will not have to go through this confusion.

**Comment by coelholm** [comment]
I've just tried with JLCPCB support to get that file without success. They said it is not possible to generate or provide details of adjusts made in their internal system, so I decided to spend some time trying to figure out by my self.

Looks like issue was related to FPC1 (Position and rotation: 51.3,28.86,-90 ) and Q1 (Rotation only: -90)

`
Designator,Val,Package,Mid X,Mid Y,Rotation,Layer

C1,100nf,SMD 0805,87.16,46.468,0,top
C2,100nf,SMD 0805,52.226,46.849,0,top
C3,10u,SMD 0805,44.06,47,90,top
FPC1,"FPC connector 40pins,  0.5mm,  TOP contacts",FH12-40S-0.5SH_1x40-1MP_P0.50mm_Horizontal_flipped,51.3,28.86,-90,top
FPC2,"FPC connector, 6 pins, 0.5mm, BOTTOM contacts",FH12-6S-0.5SH_1x06-1MP_P0.50mm_Horizontal,72.68,35.93,90,top
Q1,AO3400A ,SOT-23,42.964,8.622,-90,top
R1,8.2 Ohm,SMD 0805,40.424,13.448,90,top
R2,8.2 Ohm,SMD 0805,42.964,13.448,90,top
R3,8.2 Ohm,SMD 0805,45.504,13.448,90,top
`

**Comment by coelholm** [comment]
Those screenshots are from JLCPCB "Review Parts Placement" tool.

FPC1
![](https://raw.githubusercontent.com/coelholm/simple_stepper_motor_analyzer/main/www/Screen%20Shot%202021-07-29%20at%2017.57.34.png)

Q1
![](https://raw.githubusercontent.com/coelholm/simple_stepper_motor_analyzer/main/www/Screen%20Shot%202021-07-29%20at%2017.57.51.png)

**Comment by coelholm** [comment]
Hi @zapta 

Hope you can help me with that.

Finally I have all parts, PCB and time to assembly it (at least I thought I had all parts) . LCD and CPT came from the store listed in the BOM.xlsx, but looks like I got the wrong one, with controller R61529 instead of ILI9488.
I have installed firmware 1.0.3, but the LCD is blank, yet the backlight is on.  At serial I can see some messages, but I can't figure out if it is will be simple change or if I should just buy the correct LCD with ILI9488.

Serial output:

0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
[1500160][er:0, 0] [   -9,   -25] [en:0 0] s:2/0  steps:0 max_steps:0
DMA counters: 4394, 4394, 0`

Free memory: 49127
Options: [DEFAULT]
Pico SDK version: 1.1.2.WizIO

total_size=32768, free_cnt=3, free_size=7128, free_bigest_size=6988
used_cnt=818, max_used=26124, used_pct=79, frag_pct=2

0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
[1500160][er:0, 0] [  -12,   -26] [en:0 0] s:2/0  steps:0 max_steps:0
DMA counters: 5860, 5859, 0

Free memory: 49127
Options: [DEFAULT]
Pico SDK version: 1.1.2.WizIO

total_size=32768, free_cnt=3, free_size=7128, free_bigest_size=6988
used_cnt=818, max_used=26124, used_pct=79, frag_pct=2

**Comment by zapta** [comment]
Hi @coelholm,

1. Can you post a picture of your board, front and back.
2. What TFT are you using?  (link to source)
3. The pins of the FPC connectors bridge easily from soldering. Can you
test for shorts among adjacent pins that are not shorted in the schematic.
4. Do you happen to have an oscilloscope?

**Comment by coelholm** [comment]
Hi @zapta ,

Thank you for your help.

1.
Front
![JLCPCB front](https://raw.githubusercontent.com/coelholm/simple_stepper_motor_analyzer/main/www/WhatsApp%20Image%202021-08-26%20at%2022.58.19(1).jpeg)

Back
![JLCPCB back](https://raw.githubusercontent.com/coelholm/simple_stepper_motor_analyzer/main/www/WhatsApp%20Image%202021-08-26%20at%2022.58.19.jpeg)

2.  [Aliexpress TFT Last item: LCD and CPT](https://www.aliexpress.com/item/32376432904.html?spm=a2g0s.9042311.0.0.27424c4duNePws)

3. I have checked that visually, tested from Raspberry pins to the FPC connectors and I didn't notice any bridge. I have also assembled to boards and FPC connectors came assembled from JLCPCB. I have to solder only raspberry, current sensors and connectors for the stepper.

4. I have an oscilloscope, just let me know what you need.  It is a new tool for me, but I have a good friend to ask some help if I can't follow what you want me to do.

**Comment by zapta** [comment]
Hi @coelholm, the assembly of the PCB looks right to me. Are you sure that
your TFT panel has the ILI9488 controller?  The title and the description
on Aliexpress mention R61529 which is a different controller.

This is how my TFT looks like https://i.imgur.com/IsJELb1.png  . It's the
"3.5 LCD CTP" option here https://www.aliexpress.com/item/32862869103.html

**Comment by coelholm** [comment]
@zapta ,

It is the r61529, my mistake. I have mentioned that.

I have found a reference code for r61529 and arduino, but looking into display code for ili9488 I found some assembly code. So I have no idea on how to evaluate the effort of adding support for the r61529.

**Comment by zapta** [comment]
Hi @coelholm,  I don't expect the current firmware to support r61529.

Can you get the LCD from the link I posted?

**Comment by coelholm** [comment]
Hi @zapta,

I have ordered from the link you posted. So it should solve the problem. I appreciate your support. Thank you so much.

Just as a reference this is a basic example with initialization sequence for the R61529. [ESP32_LCD_MIPI_DBI_TYPE_B_TEST](https://github.com/daumemo/ESP32_LCD_MIPI_DBI_TYPE_B_TEST/blob/master/Arduino-Basic.cpp)

**Comment by zapta** [comment]
Thanks coelholm.

I have a r61529 display and planned to write a driver for it but am busy
and can't see how I will get to it any time soon.

The plan was to have an alternative code for this ili9488 driver
https://github.com/zapta/simple_stepper_motor_analyzer/blob/main/platformio/src/display/tft_driver.cpp#L334.
Need also to see if the pinout is compatible and if the firmware can read
and detect which TFT is in use. Otherwise, it can be set during
assembly using the reserved 'options' jumper footprints on the PCB.

Anyway, please let me know if you will encounter any problem with the new
displays.
