### ISSUE TITLE
Alternate for current sense module ACS70331EESATR-2P5B3?

### ISSUE THREAD

**Issue by pbinsted** [zapta/simple_stepper_motor_analyzer#5]
Does anyone have a source for these or an alternate that would work?

Edit - Sorry I had the wrong part. I believe the current PCB uses the ACS70331EOLCTR-2P5B3 which is the SOP-8 and appears to be available. Note this isn't listed in the current bom.

**Comment by zapta** [comment]
Have you tried https://www.aliexpress.com/item/4001123087424.html ?

**Comment by pbinsted** [comment]
Thanks so much, I believe that's exactly what I ordered. And thanks so much for the great project.
