### ISSUE TITLE
BOM is missing.

### ISSUE THREAD

**Issue by pinae** [zapta/simple_stepper_motor_analyzer#7]
README.md contains a link to a spreadsheet with the BOM: https://github.com/zapta/simple_stepper_motor_analyzer/blob/main/kicad/BOM.xlsx
This file does not exist.

Please add some information on which parts one needs to order. I understand that the files for JLPCB contain a list of components which get soldered on by the manufacturer. Are there additional components I need to buy apart from that? The FAQ mentions a Aliexpress-Link for the display without specifying which variant to order. Thereaded inserts are also mentioned but without further explanation.

**Comment by zapta** [comment]
I thought there was a BOM there, so I will look for it, maybe it got
deleted unintentionally.

In addition to the PCB and parts you get from JLCPCB, you will need a
Raspberry Pi pico module, two molex connectors (cut them using the 3D
printed jig, STL file on github), a TFT screen (needs to be a specific one,
look at the FAQ in the main page), and two current sensors (I got them from
here https://www.aliexpress.com/item/4001123087424.html , price tripled due
to the global semiconductor shortage). Also 1mm tape for the TFT (I am
using this https://www.amazon.com/gp/product/B072JJD2ND) , and M2.5 screws
and metal inserts for the 3D printed case.

Hope it helps.

**Comment by zapta** [comment]
This may be the deleted BOM file. Please see if it helps you

https://github.com/zapta/simple_stepper_motor_analyzer/blob/81e511556d2a2a73e424c4d684bd37060a49d0eb/kicad/BOM.xlsx

**Comment by pinae** [comment]
This helped al lot. Thank You!

I was able to order all the parts and the PCB.
