### ISSUE TITLE
BOM link 404s.

### ISSUE THREAD

**Issue by JRHeaton** [zapta/simple_stepper_motor_analyzer#8]
Hi, I am not able to find a BOM as the link in the readme is broken. If it was deleted would the author be willing to reupload it and verify it’s contents? I am wanting to build a few of these for my employees and want to avoid wasting money on wrong parts or time on missing parts. 

Thanks very much I look forward to hopefully hearing from you and being able to build this great tool.

**Comment by zapta** [comment]
The kicad/BOM file was deleted by mistake in a previous commit. Just added it back.  Please let me know if you have any questions.

**Comment by zapta** [comment]
... BOM rows 2-8 you can get from JLCPCB preassembled using their SMD service. Use the files in the JLCPCB directory.
