### ISSUE TITLE
current sensor orientation

### ISSUE THREAD

**Issue by legend069** [zapta/simple_stepper_motor_analyzer#9]
hi, almost finished this neat project, just need to solder on the current sensors.
it's hard to tell by looking at the photos what orientation  i need to solder the current sensors.
can you please assist.

thanks.

**Comment by globalcitizen** [comment]
<img width="1362" alt="Screen Shot 2022-04-23 at 09 13 28" src="https://user-images.githubusercontent.com/505366/164847530-f137a2fe-5d19-4e91-9425-296f2816fdc5.png">

According to current kicad sources, pin 1 should be to top right in both cases. This is indicated by the silkscreen circle on the current revision of the PCB in the kicad sources. Unsure if that's the same version you used.

If unsure, double-check the opposite pin (pin 5 = other side of IC and other end of IC) should have a via to GND.

**Comment by zapta** [comment]
Yes, both dots are upper right in that orientation.

https://i.imgur.com/kfjeOYc.png
